/*
===============================================================================
Measures Exploration (Key Metrics)
===============================================================================
Purpose:
    - To calculate aggregated metrics (e.g., totals, averages) for quick insights.
    - To identify overall trends or spot anomalies.

SQL Functions Used:
    - COUNT(), SUM(), AVG()
===============================================================================
*/
-- Report 

SELECT 'total_sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales

UNION ALL 

SELECT 'total_quantity' AS measure_name, COUNT(quantity) AS measure_value FROM gold.fact_sales

UNION ALL 

SELECT 'total_orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales

UNION ALL 

SELECT 'total_products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM gold.dim_products

UNION ALL 

SELECT 'total_customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.dim_customers

UNION ALL 

SELECT 'total_customers_with_orders' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales

-- Find total customers by countries
SELECT 
	country, COUNT(customer_key) total_customers 
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT 
	gender, 
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category 
SELECT 
	category, 
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT
	category,
	AVG(product_cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated by each category?
SELECT 
	dp.category,
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC

-- Find the total revenure generated by each customer.
SELECT	
	dc.customer_key,
	dc.first_name, 
	dc.last_name, 
	SUM(fs.sales_amount) total_revenue 
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY	
	dc.customer_key,
	dc.first_name, 
	dc.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold itmes across countries?
SELECT 
	dc.country, 
	COUNT(fs.quantity) total_items
FROM gold.dim_customers AS dc
LEFT JOIN gold.fact_sales AS fs
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_items DESC

-- Which five products generate the highest revenue?
SELECT TOP 5
	dp.product_name, 
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue DESC

-- What are the 5 worst performing products in terms of sales
SELECT TOP 5
	dp.product_name, 
	SUM(fs.sales_amount) total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue ASC

-- Find the top 10 customers who have generated the highest revenue 

SELECT TOP 3 
	dc.customer_key,
	COUNT( DISTINCT fs.order_number) total_orders
FROM gold.dim_customers dc
LEFT JOIN gold.fact_sales fs 
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key
ORDER BY total_orders 
